import { defineConfig, type ViteDevServer } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import type { IncomingMessage, ServerResponse } from 'http'

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Vite plugin to save icons generated by canvas in the browser
function iconSaverPlugin() {
  return {
    name: 'icon-saver',
    configureServer(server: ViteDevServer) {
      server.middlewares.use((req: IncomingMessage, res: ServerResponse, next: () => void) => {
        if (req.url === '/api/save-icon' && req.method === 'POST') {
          let body = '';
          req.on('data', (chunk: Buffer) => {
            body += chunk.toString();
          });
          req.on('end', () => {
            try {
              const { filename, base64Data } = JSON.parse(body);
              const buffer = Buffer.from(base64Data.split(',')[1], 'base64');
              const publicDir = path.resolve(__dirname, 'public');
              const filePath = path.join(publicDir, filename);
              
              fs.writeFileSync(filePath, buffer);
              console.log(`[Icon Saver] Saved ${filename} to ${filePath}`);
              
              res.writeHead(200, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ success: true }));
            } catch (err: any) {
              console.error('[Icon Saver] Error saving icon:', err);
              res.writeHead(500, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ error: err?.message || 'Unknown error' }));
            }
          });
        } else {
          next();
        }
      });
    }
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), iconSaverPlugin()],
})

